
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email": "caaa@gmail.com",
    "password": "123589753"
}

###

POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "cazinha@gmail.com",
    "password": "123589753"
}

###

GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: 
###
