//Create User
POST http://localhost:3003/user/signup
Content-Type: application/json

{
  "name" : "Carlise Lima",
  "email" : "caca@gmail.com",
  "password" : "123456",
  "role" : "ADMIN"
}
### 

// login 
POST http://localhost:3003/user/login
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzZGYyNzFmLWJkYWEtNDEwNy05MGYxLTBkNDA5ZjMyNWFjZiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTYxNzI0NSwiZXhwIjoxNjUxNjE3ODQ1fQ.sm3HVKGras5q2cmW2o77-XH4NRF0_nF4oRmLPhZf2Mk

{
"email" : "caca@gmail.com", 
"password" : "123456"
}

### 

//Buscar dados do perfil usuário
GET http://localhost:3003/user/c3df271f-bdaa-4107-90f1-0d409f325acf
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwYmVkZWJmLWI1OGItNDY0My04ODNiLTBmNDE2MGFlMTY2YSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTYzNzU1MywiZXhwIjoxNjUxNjk3NTUzfQ.yAVD7hykeHYn_fU7J7v3OUoA3FxF9Jzm5bbTXTKN924
### 

// criar receitas
POST http://localhost:3003/user/recipe/c3df271f-bdaa-4107-90f1-0d409f325acf
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwYmVkZWJmLWI1OGItNDY0My04ODNiLTBmNDE2MGFlMTY2YSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTYzNzU1MywiZXhwIjoxNjUxNjk3NTUzfQ.yAVD7hykeHYn_fU7J7v3OUoA3FxF9Jzm5bbTXTKN924

{
	"titulo": "Bolo fofo de laranja",
	"descricao": " Ingredientes - Massa 3 ovos, 2 colheres de sopa de margarina, 1 xícara de açúcar, 2 xícaras de farinha de trigo, 1 xícara de suco de laranja, 1 colher de sopa de fermento. Ingredientes - Calda: 1 xícara de açúcar, Meia xícara de suco de laranja",
  "modo_de_preparo" : " 1. Em uma tigela, coloque 3 ovos, 2 colheres de sopa de margarina e 1 xícara de açúcar. Misture. 2. Em seguida, acrescente 2 xícaras de farinha de trigo e misture novamente. 3. Depois, despeje 1 xícara de suco de laranja na tigela e misture novamente.     4. Por fim, adicione 1 colher de sopa de fermento e misture novamente. 5. Transfira a massa para uma forma redonda com furo. 6. Leve para assar em forno preaquecido a 180 graus Celsius por 30 minutos."
}
### 

//Buscar receita por id
GET http://localhost:3003/recipe/4ff0cc41-22dd-43cc-b193-5ec593ebae47
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwYmVkZWJmLWI1OGItNDY0My04ODNiLTBmNDE2MGFlMTY2YSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTYzNzU1MywiZXhwIjoxNjUxNjk3NTUzfQ.yAVD7hykeHYn_fU7J7v3OUoA3FxF9Jzm5bbTXTKN924
### 

// seguidores
POST http://localhost:3003/user/seguidores
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwYmVkZWJmLWI1OGItNDY0My04ODNiLTBmNDE2MGFlMTY2YSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTYzNzU1MywiZXhwIjoxNjUxNjk3NTUzfQ.yAVD7hykeHYn_fU7J7v3OUoA3FxF9Jzm5bbTXTKN924


{
	"followed_id" : "d193d0f3-b242-48be-8481-ffc79a5ec8cc"
}
### 

//Buscar perfil
GET http://localhost:3003/perfil
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwYmVkZWJmLWI1OGItNDY0My04ODNiLTBmNDE2MGFlMTY2YSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTYzNzU1MywiZXhwIjoxNjUxNjk3NTUzfQ.yAVD7hykeHYn_fU7J7v3OUoA3FxF9Jzm5bbTXTKN924
### 