GET http://localhost:3003/user
Content-Type: application/json

####

GET http://localhost:3003/user/name?name=Aline
Content-Type: application/json

####


GET http://localhost:3003/user/CX
Content-Type: application/json

####

GET http://localhost:3003/user/order
Content-Type: application/json

####


/user/order