POST http://localhost:3003/create
Content-Type: application/json

{
    
    "cep": 90680570 ,
    "logradouro": "Aparicio Borges",
    "numero": 1010,
    "complemento": "atp 302",
    "bairro": "Lume",
    "cidade": "Roca Sales",
    "estado": "RS"
}
###