POST http://localhost:3003/users
Content-Type: application/json

{
    
    "name": "Gustavo Lume" ,
    "email": "gulume@gmail.com",
    "password": "5687p3e"
}
###

GET http://localhost:3003/users
Content-Type: application/json
###